# Generated by Django 3.1.1 on 2020-09-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheese',
            old_name='firmnes',
            new_name='firmness',
        ),
    ]
